### ISSUE TITLE
Please enter product SKU

### ISSUE THREAD

**Issue by Evgenas** [Sylius/Sylius-Sandbox#89] opened 2012-12-19 14:06 UTC
currently when try create new product  error appear: "Please enter product SKU"

**Comment by umpirsky** [comment] 2012-12-19 14:08
This is a duplicate of #82.

Thanks for reporting it.

**Comment by pjedrzejewski** [comment] 2012-12-19 16:09
Closing this one then, I fixed it and it should see the light today.

**Closed as completed by pjedrzejewski** 2012-12-19 16:09 UTC
