### ISSUE TITLE
Error when open sylius

### ISSUE THREAD

**Issue by miglsilva** [Sylius/Sylius-Sandbox#64] opened 2012-10-18 16:24 UTC
Hi.

I have try to experience the project sylius. I clone the project with git and add the composer to add vendors and also create the database. 

When i try to open the website i saw the error on live document on logs.

"SQLSTATE[42000] [1044] Access denied for user ''@'localhost' to database 'sylius_sandbox'"

Can anyone give me some help.

Thank you in advance.

Miguel Silva

**Comment by pjedrzejewski** [comment] 2012-10-20 07:46
Hey! You need to copy the `parameters.yml.dist` to `parameters.yml` and configure your own values, looks like you have left the database user field blank. Both files should live inside `sandbox/config/container` directory. Let me know if that helped, thanks!

**Comment by miglsilva** [comment] 2012-10-20 18:42
Hi Pawel, 

Thank you very much for the reply. I have already do that as i show below:

parameters:
    sylius.url:               http://sylius-sandbox.localhost/dev.php

```
sylius.database.driver:   pdo_mysql
sylius.database.host:     localhost
sylius.database.port:     null
sylius.database.name:     sylius_sandbox_dev
sylius.database.user:     sylius
sylius.database.password: null

sylius.mailer.transport:  smtp
sylius.mailer.host:       localhost
sylius.mailer.user:       null
sylius.mailer.password:   null

sylius.locale: en

sylius.secret: 7105d4542c26b7dec214bfab78d8da51b
```

I change all parameters in the parameters.yml but the error continues and if i change some parameter i don't see any changes on the log of the error.

Thank you in advance.
Miguel Silva.

**Comment by pjedrzejewski** [comment] 2012-10-20 18:43
Really strange, I'll try to reproduce the problem and let you know about the result. I have no idea why it does not work...

**Comment by miglsilva** [comment] 2012-10-21 22:02
Hi Pawel,

I solved the problem hardcoded the name of the username on the file PDOMySqll/Driver.php 

```
    if (isset($params['dbname'])) {
        $dsn .= 'dbname=' . 'sylius_sandbox_dev'. ';';
```

And on the PDOConnection.php  

```
    parent::__construct($dsn, 'root', $password, $options);
```

This turn possible see the first page of the project i open the url http://localhost/Sylius-Sandbox/public/index.php but when i click in on link they doesn't work.

I install the project by sylius-sandbox 

Quick installation
Clone this repository with this command.

$ git clone http://github.com/Sylius/Sylius-Sandbox.git
Open sandbox/config/container/parameters.yml.dist, set your values and save as parameters.yml.

Install dependencies using composer.

$ wget http://getcomposer.org/composer.phar
$ php composer.phar install
Create database schema and dump assetic assets by typing following commands inside console.

$ ./bin/rebuild-database
$ php sandbox/console assetic:dump
Open up /path/to/Sylius-Sandbox/public/dev.php in your browser and play with the application.

If i try to open the dev.php i receive this error:

SCREAM: Error suppression ignored for
( ! ) Fatal error: Maximum execution time of 30 seconds exceeded in D:\wamp\www\Sylius-Sandbox\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Compiler\ReplaceAliasByActualDefinitionPass.php on line 106

Thank you in advance.
Miguel Silva

**Comment by pjedrzejewski** [comment] 2012-11-29 17:53
Hey! Can you clarify if the issue still exists? Thank you.

**Comment by miglsilva** [comment] 2012-11-29 22:18
Hey, 

Thank you very much for the support. I already now what happened.

Thank you.
Miguel Silva

**Comment by pjedrzejewski** [comment] 2012-11-30 08:16
Great! Closing this then. :) Feel free to open more issues if any problems.

**Closed as completed by pjedrzejewski** 2012-11-30 08:16 UTC

**Comment by goemaere** [comment] 2015-04-28 19:43
@miglsilva how did you solve this problem? i am experiencing the same on my local dev pc

Edit: found it out myself. It's because I was using a vagrant environment in windows. The use of SMB to share a drive between vagrant and windows is way too slow for projects with a lot of files. Use rsync (vagrant supports rsync-auto) and put the cache/log dir outside of the shared folder.

More info: 
http://www.whitewashing.de/2013/08/19/speedup_symfony2_on_vagrant_boxes.html
http://docs.vagrantup.com/v2/cli/rsync-auto.html
